BUG-1603 : Add missing dependency
2017-12-18T09:14:27.007+02 ERROR {} [http-bio-8302-exec-56] ERROR org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/tarjonta-app].[default]: Servlet.service() for servlet [default] in context with path [/tarjonta-app]
 threw exception
java.lang.RuntimeException: Unable to create XMLReader
        at org.jasig.cas.client.util.XmlUtils.getXmlReader(XmlUtils.java:44)
        at org.jasig.cas.client.util.XmlUtils.getTextForElement(XmlUtils.java:116)
        at org.jasig.cas.client.validation.Cas20ServiceTicketValidator.parseResponseFromServer(Cas20ServiceTicketValidator.java:69)
        at org.jasig.cas.client.validation.AbstractUrlBasedTicketValidator.validate(AbstractUrlBasedTicketValidator.java:188)
        at org.springframework.security.cas.authentication.CasAuthenticationProvider.authenticateNow(CasAuthenticationProvider.java:158)
        at org.springframework.security.cas.authentication.CasAuthenticationProvider.authenticate(CasAuthenticationProvider.java:143)
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174)
        at org.springframework.security.cas.web.CasAuthenticationFilter.attemptAuthentication(CasAuthenticationFilter.java:270)
        at fi.vm.sade.security.CustomCasAuthenticationFilter.atttempAuthenticationInternal(CustomCasAuthenticationFilter.java:110)
...
Caused by: org.xml.sax.SAXException: SAX2 driver class org.apache.xerces.parsers.SAXParser not found
        at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:230)
        at org.xml.sax.helpers.XMLReaderFactory.createXMLReader(XMLReaderFactory.java:191)
        at org.jasig.cas.client.util.XmlUtils.getXmlReader(XmlUtils.java:42)
        ... 47 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1891)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1734)
        at org.xml.sax.helpers.NewInstance.newInstance(NewInstance.java:82)
        at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:228)
        ... 49 common frames omitted